GET http://localhost:5000/notebook

###
POST http://localhost:5000/add-notes
Content-Type: application/json

{
    "notes": "Test",
    "picture": ""
}

###
PUT http://localhost:5000/edit-users/2
Content-Type: application/json

{
    "name": "Vincent",
    "email": "vincent@gmail.com",
    "gender": "Male"
}

###
DELETE http://localhost:5000/delete-users/1

 